on_site_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :traumas
  resources :first_aid_items
  resources :posts

  get "/", to: "home#index"
  get "/traumas", to: "traumas#index"
  get "/traumas/:id", to: "traumas#show"

  get "/first_aid", to: "first_aid_items#index"
  get "/first_aid/:id", to: "first_aid_items#show"

  resources :posts do
  end


    put "like/:id", to: "posts#upvote", as: :like
    put "dislike/:id", to: "posts#downvote", as: :dislike

end

on_site_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

on_site_app/app/models/first_aid_item.rb
class FirstAidItem < ApplicationRecord
  has_many :traumas, through: :traumas_items
end

on_site_app/app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  validates :content, presence: true, length: { maximum: 320,
  too_long: "%{count} characters is the maximum allowed" }

end

# @post = Post.new(:title => 'my post!')
# @post.save

# @post.liked_by @session
# @post.votes_for.size # => 1

# @post.votes_for.up.by_type(User)
# @post.votes_for.down
# @user1.votes.up
# @user1.votes.down
# @user1.votes.up.by_type(Post)

on_site_app/app/models/session.rb
class Session < ApplicationRecord
  acts_as_voter
end

on_site_app/app/models/trauma.rb
class Trauma < ApplicationRecord
  has_many :first_aid_items, through: :traumas_items
end

on_site_app/app/models/trauma_item.rb
class TraumaItem < ApplicationRecord
  # belongs_to :traumas
  # belongs_to :first_aid_items
end

on_site_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

on_site_app/app/controllers/first_aid_items_controller.rb
class FirstAidItemsController < ApplicationController

  def index
    @first_aid_items = FirstAidItem.all
  end

  def show
    @first_aid_items = FirstAidItem.all
    @first_aid_item = FirstAidItem.find(params[:id])
  end

  def first_aid_items_param
    params.require(:first_aid_item).permit(:name, :instructions, :first_aid_item_id)
  end

end

on_site_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    Session.create(:whatever => 'whatever')
  end
end

on_site_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order("cached_votes_up DESC")
  end

  def new
    @post = Post.find(params[:post_id])
    @post = Post.new
    @post.save
  end

  def create
    # @post = Post.find(params[:post_id])
    Post.create(title: params[:title],
            content: params[:content])
    #redirect_to post_path(@post)
    redirect_to :back
  end

  def upvote
    @post = Post.find(params[:id])
    # @session = Session.find_by(:id => $1)
    @session = Session.last
    # @post.upvote
    # @post.upvote_from current_user
    # @session[:voting_id].to_i ||= create_unique_voting_id
    @post.upvote_by @session
    # (session_id: session["id"], user_id: current_user.id).first
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    # @session = Session.find_by(:id => $1)
    @session = Session.last
    @post.downvote_by @session
    # @post.downvote
    # @post.downvote_from current_user
    redirect_to :back
  end

end

on_site_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

on_site_app/app/controllers/traumas_controller.rb
class TraumasController < ApplicationController

  def index
    @traumas = Trauma.all
  end

  def show
    @trauma = Trauma.find(params[:id])
    # @trauma_item = TraumaItem.find_by(params[:id])
    @traumas_items = TraumaItem.all
    @first_aid_items = FirstAidItem.all
    # @first_aid_item = FirstAidItem.find(params[:id])
  end

end

on_site_app/app/controllers/traumas_items_controller.rb
class TraumasItemsController < ApplicationController
end

on_site_app/app/helpers/application_helper.rb
module ApplicationHelper
end

on_site_app/app/helpers/first_aid_items_helper.rb
module FirstAidItemsHelper
end

on_site_app/app/helpers/home_helper.rb
module HomeHelper
end

on_site_app/app/helpers/posts_helper.rb
module PostsHelper
end

on_site_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

on_site_app/app/helpers/traumas_helper.rb
module TraumasHelper
end

on_site_app/app/helpers/traumas_items_helper.rb
module TraumasItemsHelper
end

on_site_app/app/views/first_aid_items/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="/assets/stylesheets/application.css">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>
<body>

  <nav class="red darken-3" role="navigation">
    <ul class="right hide-on-med-and-down">
      <li><a href="/traumas">Trauma List</a></li>
      <li><a href="/posts">Channel</a></li>
    </ul>

      <ul id="nav-mobile" class="brand-logo center">
        <li><a href="/" class="home_logo">On Site</a></li>
      </ul>
    </div>
  </nav>

  <img src=<%=image_path("first-aid-kit-for-your-home (2).jpg")%>  height="720" width="1280r" usemap="#Map" border="0" alt="Null" />

  <map name="Map" >

    <% @first_aid_items.each do |x| %>
      <area id="<%=x[:name]%>" shape="poly" coords="<%= x[:coords] %>" href="/first_aid/<%= x[:id] %>" alt="adhesive">
    <% end %>

  </map>

</body>
</html>

on_site_app/app/views/first_aid_items/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="/app/assets/images">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>
<body>

  <nav class="red darken-3" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo">Home</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/first_aid">First Aid Kit</a></li>
        <li><a href="/traumas">Trauma List</a></li>
        <li><a href="/posts">Channel</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="/">Home</a></li>
      </ul>
    </div>
  </nav>
  <h1><%= @first_aid_item.name %> </h1>

  <div class="first_aid_show">
    <p> <b>Instructions for Use:</b> <%= @first_aid_item.instructions %></p>
    <p> <b>Use Cases:</b> <%= @first_aid_item.uses %></p>
  </div>

  <div class="item_image">
    <img src=<%= "/assets/#{@first_aid_item.image}" %> />
  </div>

</body>
</html>

on_site_app/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>
<body>

  <nav class="red darken-3" role="navigation">
    <ul class="right hide-on-med-and-down">
      <li><a href="/first_aid">First Aid Kit</a></li>
      <li><a href="/traumas">Trauma List</a></li>
      <li><a href="/posts">Channel</a></li>
    </ul>

      <ul id="nav-mobile" class="brand-logo center">
        <li><a href="/" class="home_logo">On Site</a></li>
      </ul>
  </nav>

  <img src=<%=image_path("travel-first-aid-kid.jpg")%> style='width:100%;' border="0" alt="Null"/>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="js/materialize.min.js"></script>
</body>

on_site_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

on_site_app/app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="/assets/stylesheets/application.css">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>

  <nav class="red darken-3" role="navigation">
    <ul class="right hide-on-med-and-down">
      <li><a href="/first_aid">First Aid Kit</a></li>
      <li><a href="/traumas">Trauma List</a></li>
    </ul>

      <ul id="nav-mobile" class="brand-logo center">
        <li><a href="/" class="home_logo">On Site</a></li>
      </ul>
    </div>
  </nav>

<div class="post_form">
<form action="/posts" method='POST'>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <b>Post Title</b>  <input type="text" name="title" wrap="hard" rows="2" cols="20">
  <b>Your Story</b> <input type="text" name="content">
  <input type="submit">
</form></div>
<br>

  <div class="siren">
  <span><iframe src="https://giphy.com/embed/9c9Qa5kocGqru" width="80" height="80" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/sirens-9c9Qa5kocGqru"></a></p>
  NIST Telephone Time-of-Day Service<br>
  <a href="tel:+911">Call</a> 911 Emergency Services Now</span>
  </div>

<div class="post_container">
<% @posts.each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= post.content %><br>
      <br>Submitted <%= time_ago_in_words(post.created_at) %>
    </p>

  <%= link_to like_path(post), method: :put do %>
    <i class="material-icons" id="material-icons-up">thumb_up</i>
    <%= post.get_upvotes.size %>
  <% end %><br>

  <%= link_to dislike_path(post), method: :put do %>
    <i class="material-icons" id="material-icons-down">thumb_down</i>
    <%= post.get_downvotes.size %>
  <% end %><br>


<% end %><br>
</div>

</body>
</html>

on_site_app/app/views/traumas/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="/assets/stylesheets/application.css">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>
<body>

  <nav class="red darken-3" role="navigation">
    <ul class="right hide-on-med-and-down">
      <li><a href="/first_aid">First Aid Kit</a></li>
      <li><a href="/posts">Channel</a></li>
    </ul>

      <ul id="nav-mobile" class="brand-logo center">
        <li><a href="/" class="home_logo">On Site</a></li>
      </ul>
    </div>
  </nav>

<div class="trauma_show">
<h1>Trauma List</h1>

<% @traumas.each do |trauma| %>
  <div>
    <a href="/traumas/<%= trauma.id %>"><%= trauma.name %></a>
  </div>
<% end %>
</div>

</body>
</html>

on_site_app/app/views/traumas/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title></title>
  <link rel="stylesheet" href="/assets/stylesheets/application.css">
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
</head>
<body>

  <nav class="red darken-3" role="navigation">
    <ul class="right hide-on-med-and-down">
      <li><a href="/first_aid">First Aid Kit</a></li>
      <li><a href="/traumas">Trauma List</a></li>
      <li><a href="/posts">Channel</a></li>
    </ul>

      <ul id="nav-mobile" class="brand-logo center">
        <li><a href="/" class="home_logo">On Site</a></li>
      </ul>
    </div>
  </nav>

<div class="trauma_show">
</html><h1> <%= @trauma.name %> </h1>

<p> <b>Instructions:</b> <%= @trauma.instructions %></p>


   <% @first_aid_items.each do |x| %>
      <area id="<%=x[:name]%>" href="/first_aid/<%= x[:id] %>">
    <% end %>
    </div>


</body>